name: .NET

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/${env:RELEASE_BRANCH}
        env:
          RELEASE_BRANCH: master

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: 
          echo ${{ env.GITHUB_HEAD_REF_SLUG }}
          dotnet build --no-restore --configuration Release /p:Version=${env:VERSION}
        env:
          VERSION: ${GITHUB_REF/refs\/tags\/v/}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${env:VERSION} --no-build
        env:
          VERSION: ${GITHUB_REF/refs\/tags\/v/}

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${env:VERSION}" --no-build --output .
        env:
          VERSION: ${GITHUB_REF/refs\/tags\/v/}

      - name: Push
        run: dotnet nuget push NuGet.Workflow.${env:VERSION}".nupkg --source https://nuget.pkg.github.com/topdownproteomics/index.json --api-key ${env:GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_KEY }}
          VERSION: ${GITHUB_REF/refs\/tags\/v/}
